
discrete:
  # dts
  control_dt: 0.1 # s
  predict_dt: 0.1
  t_horizon: 2.0 # s
  delta_v: 0.15
  delta_w: 0.1 # rad/s

dynamics:
  # linear and angular speed limits for the robot
  v_max: 1.5 # m/s
  v_min: 0.0 # m/s
  w_max: 1.0 # rad/s
  w_min: -1.0 # rad/s

